version: '3.8'
services:
  express-backend:
    build: .
    command: sh -c "npm install && nodemon Server.js"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  vite-frontend:
    image: node:21.6.1
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    working_dir: /app
    depends_on:
      - express-backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1-amd64
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=Frd!@#123
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
